kind: Service
apiVersion: v1
metadata:
  name: train-schedule-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: train-schedule
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30001
  externalIPs:
  - 13.52.238.77
  - 52.53.196.15

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-schedule-deployment
  labels:
    app: train-schedule
spec:
  replicas: 2
  selector:
    matchLabels:
      app: train-schedule
  template:
    metadata:
      labels:
        app: train-schedule
    spec:
      containers:
      - name: train-schedule
        image: ldfoskey007/train-schedule:latest
        ports:
        - containerPort: 8080
