kind: Service
apiVersion: v1
metadata:
  namespace: train-schedule
  name: train-schedule-service
spec:
  type: NodePort
  selector:
    app: train-schedule
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 8080
    nodePort: 32502
  externalIPs:
    - 13.52.250.161
    - 50.18.242.71  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: train-schedule
  name: train-schedule-deployment
  labels:
    app: train-schedule
spec:
  replicas: 2
  selector:
    matchLabels:
      app: train-schedule
  template:
    metadata:
      labels:
        app: train-schedule
    spec:
      containers:
      - name: train-schedule
        image: ldfoskey007/train-schedule:latest
        ports:
        - containerPort: 8080
       
