kind: Service
apiVersion: v1
metadata:
  namespace: train-schedule
  name: train-schedule-service
  labels:
    app: train-schedule
    name: train-schedule
    disktype: ssd
spec:
  type: NodePort
  selector:
    app: train-schedule
    name: train-schedule
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 8080
  externalIPs:
  - 50.18.78.206
  - 54.241.87.150    
    
---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: train-schedule
  name: train-schedule-deployment
  labels:
    app: train-schedule
    name: train-schedule
    disktype: ssd
spec:
  replicas: 2
  selector:
     matchLabels:
       app: train-schedule
       name: train-schedule
  template:
    metadata:
      labels:
        app: train-schedule
        name: train-schedule
    spec:
      containers:
      - name: train-schedule-container
        image: ldfoskey007/train-schedule:latest
        ports:
        - containerPort: 8080
      nodeSelector:
        disktype: ssd
       
