kind: Service
apiVersion: v1
metadata:
  namespace: train-schedule
  name: train-schedule-service
  labels:
    app: train-schedule
spec:
  type: NodePort
  selector:
    app: train-schedule
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  externalIPs:
  - 54.177.78.220
  - 18.144.89.48
    
    
---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: train-schedule
  name: train-schedule-deployment
  labels:
    app: train-schedule
spec:
  replicas: 2
  selector:
     matchLabels:
       app: train-schedule
  template:
    metadata:
      labels:
        app: train-schedule
    spec:
      containers:
      - name: train-schedule-container
        image: ldfoskey007/train-schedule:latest
        ports:
        - containerPort: 8080
       
