kind: Service
apiVersion: v1
metadata:
  namespace: train-schedule
  name: train-schedule-service
  labels:
    app: train-schedule
    name: train-schedule    
spec:
  type: NodePort
  selector:
    app: train-schedule
    name: train-schedule
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 8081
  externalIPs:
  - 3.101.74.179
  - 54.67.123.81    
    
---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: train-schedule
  name: train-schedule-deployment
  labels:
    app: train-schedule
    name: train-schedule    
spec:
  replicas: 2
  selector:
     matchLabels:
       app: train-schedule
       name: train-schedule
  template:
    metadata:
      labels:
        app: train-schedule
        name: train-schedule
    spec:
      containers:
      - name: train-schedule-container
        image: ldfoskey007/train-schedule:latest
        ports:
        - containerPort: 8081   
